'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SystemSales.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_99yygXrRR8ix1wDOsdjLKA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1_99yygXrRR8ix1wDOsdjLKA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1028_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1028-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _13_Famous_Business_Leaders_You_Must_Follow_in_2022() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13_Famous_Business_Leaders_You_Must_Follow_in_2022", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _14117805() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("14117805", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2023_hottest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2023 hottest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _322278877_821247718973237_3877896043016079321_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("322278877_821247718973237_3877896043016079321_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _374b076a_99a1_49cb_96a4_2c1db9f96724() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("374b076a-99a1-49cb-96a4-2c1db9f96724", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4841747() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4841747", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _48417471() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("48417471", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _522_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("522-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _59f71a0b_8f4a_4746_a18b_b8f6e5817588() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("59f71a0b-8f4a-4746-a18b-b8f6e5817588", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6678_png_860() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6678.png_860", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6714f446_8c5f_4aa2_9560_b2216ed8bfb9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6714f446-8c5f-4aa2-9560-b2216ed8bfb9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6714f446_8c5f_4aa2_9560_b2216ed8bfb9__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6714f446-8c5f-4aa2-9560-b2216ed8bfb9 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _83da7eec_338e_4152_8e25_bf190db99f62() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("83da7eec-338e-4152-8e25-bf190db99f62", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _861b3844485fa9292a8110005dce5d4a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("861b3844485fa9292a8110005dce5d4a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8cce8ee2_37f6_4a69_bd00_67f94831207b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8cce8ee2-37f6-4a69-bd00-67f94831207b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8ef980b2_33f6_40eb_ba78_fb6e92a200ec() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8ef980b2-33f6-40eb-ba78-fb6e92a200ec", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8ef980b2_33f6_40eb_ba78_fb6e92a200ec1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8ef980b2-33f6-40eb-ba78-fb6e92a200ec1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _960x0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("960x0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _960x0__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("960x0 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _960x01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("960x01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _960x02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("960x02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _99a42002_c907_47cd_bdf7_99fbdab63e95() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("99a42002-c907-47cd-bdf7-99fbdab63e95", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property b9ee81d0ac3dd35a5bfa7af9011e66d8fdbde911() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b9ee81d0ac3dd35a5bfa7af9011e66d8fdbde911", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bc968e9c_300f_4d1d_b725_77eef90805a8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bc968e9c-300f-4d1d-b725-77eef90805a8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bfe57249_e7b2_4fef_a29c_c42dadcb593d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bfe57249-e7b2-4fef-a29c-c42dadcb593d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bh_advisor_dribbble() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bh-advisor-dribbble", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property business_application_addmale_useradd_insert_add_user_client_2312() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("business_application_addmale_useradd_insert_add_user_client_2312", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property business_application_addmale_useradd_insert_add_user_client_23121() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("business_application_addmale_useradd_insert_add_user_client_23121", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property business_development_data() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("business-development-data", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property business_development_data1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("business-development-data1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property business_intelligence() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("business-intelligence", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property business_världen_54072622() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("business_världen_54072622", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property business_världen_54072622__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("business_världen_54072622 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property business_världen_540726221() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("business_världen_540726221", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Capture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Capture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Capture1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Capture1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ce205609_1f48_4384_b87f_da9e08096b6a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ce205609-1f48-4384-b87f-da9e08096b6a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Competitive_Advantage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Competitive-Advantage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property db6627f766186e082546671e00e5f0ab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("db6627f766186e082546671e00e5f0ab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eeca7e78_dd90_493b_a54f_1ae64180b5fe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eeca7e78-dd90-493b-a54f-1ae64180b5fe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Engineering_Solutions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Engineering-Solutions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flat_seo_30_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flat_seo-30-512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flat_seo_30_5121() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flat_seo-30-5121", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flat_seo_30_5122() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flat_seo-30-5122", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property G0B8tUMTQIOpBkg3tBeK_ThinkstockPhotos_174284055() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("G0B8tUMTQIOpBkg3tBeK_ThinkstockPhotos-174284055", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property giphy1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("giphy1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property global_business() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("global-business", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IncrementalInnovation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncrementalInnovation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ontario_Automotive_Modernization_Program_Sharpening_your_competitive_edge_2048x1368() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ontario-Automotive-Modernization-Program_Sharpening-your-competitive-edge-2048x13"& _ 
                        "68", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ontario_Automotive_Modernization_Program_Sharpening_your_competitive_edge_2048x13681() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ontario-Automotive-Modernization-Program_Sharpening-your-competitive-edge-2048x13"& _ 
                        "681", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property other_biz_growth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("other-biz-growth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_business_people_holding_dollar_bills_action_photography_chart_technology_finance_picture_image_1491471() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-business-people-holding-dollar-bills-action-photography-chart-technology-"& _ 
                        "finance-picture-image_1491471", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_city_earth_internet_data_blue_background_picture_image_930022() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-city-earth-internet-data-blue-background-picture-image_930022", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_earth_sunrise_business_poster_background_picture_image_1055207() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-earth-sunrise-business-poster-background-picture-image_1055207", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_global_business_people_team_silhouettes_picture_image_1774323() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-global-business-people-team-silhouettes-picture-image_1774323", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_internet_security_background_picture_image_466921() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-internet-security-background-picture-image_466921", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_man_in_business_suit_as_user_icon_isolated_png_image_1999567() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-man-in-business-suit-as-user-icon-isolated-png-image_1999567", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_no_cellphone_forbidden_sign_png_image_1722095() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-no-cellphone-forbidden-sign-png-image_1722095", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_no_cellphone_forbidden_sign_png_image_17220951() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-no-cellphone-forbidden-sign-png-image_17220951", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property R__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("R (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property R1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("R1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property R2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("R2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property R3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("R3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SaaS_Business_Growth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaaS-Business-Growth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screenshot__15_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screenshot (15)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property transformation_of_industries_in_2023() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transformation-of-industries-in-2023", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property transformation_of_industries_in_2023__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transformation-of-industries-in-2023 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property transparent_cart_icon_online_shop_icon_60329202a59827_2944215016139269146783() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transparent-cart-icon-online-shop-icon-60329202a59827.2944215016139269146783", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_is_systems_engineering_cover_art_01_1024x386() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What-is-systems-engineering-cover-art-01-1024x386", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property what_is_the_difference_between_a_bba_in_accounting_and_a_bs_in_accounting_1024x683_1_780x470() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("what-is-the-difference-between-a-bba-in-accounting-and-a-bs-in-accounting-1024x68"& _ 
                        "3-1-780x470", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property استلام_نقديه() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("استلام-نقديه", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property الاصناف_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("الاصناف-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property العملاء() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("العملاء", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property الموردين2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("الموردين2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property الموظفين_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("الموظفين-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property بيان_اسعار_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("بيان-اسعار-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property تخصصات_الهندسة_الميكانيكية() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("تخصصات_الهندسة_الميكانيكية", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property حضور_وانصراف1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("حضور-وانصراف1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property خدمه_العملاء() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("خدمه العملاء", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property دفع_نقديه() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("دفع-نقديه", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property فتوره_مشتريات1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("فتوره-مشتريات1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property مرتجع_مشتريات() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("مرتجع مشتريات", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ملاك() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ملاك", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
